apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: isthissiteup
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: isthissiteup
spec:
  source:
    git:
      url: https://github.com/msrinivasssa/isthesiteup.git
      ref:
        branch: main
