apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: isthissiteup
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: isthissiteup
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  source:
    git:
      url: https://github.com/msrinivasssa/isthesiteup.git
      ref:
        branch: main
